### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by fossilet** [landonth/github-desktop-protocol-fix#1]
In the console of Safari, this error occurs:

> Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy.

**Comment by davidherzina** [comment]
@fossilet I created Safari extension (https://github.com/forCandies/GithubDesktopProtocol)

**Comment by fossilet** [comment]
@davidherzina it works, thanks.

**Comment by loopervfx** [comment]
@davidherzina thanks much for the safari extension, as i wasn't able to get around safari's security policy via tampermonkey.

closing this issue.
